<?php

include_once('atrium_readingresponse.features.inc');

/**
 * Implementation of hook_help().
 */
function atrium_readingresponse_help($path) {
  // Central help page content.
  if ($path == 'help#atrium_readingresponse') {
    $help = '<h3>'. t('Reading Response') .'</h3>';
    $help .= '<p>'. t("The readingresponse lets your team communicate by posting updates and discussing issues. It is a great place for sharing progress, discussing challenges, and exploring ideas.") .'</p>';
    $help .= '<p>'. t("To start a conversation navigate to the readingresponse and click the \"Add readingresponse post\" button. You will need to enter a title and some body content to your post. Then click \"Save\".") .'</p>';
    return $help;
  }

  // Contextual help content.
  if (context_isset('context', 'readingresponse_listing')) {
    if ($path == 'node/add/readingresponse') {
      $help = '';
      $help .= '<h3>'. t('Reading Response') .'</h3>';
      $help .= '<p>'. t("Post an entry to the readingresponse of this group. The post will be shared will all team members on the readingresponse, and they will be able to reply to it. You can optionally notify other group members by checking their name in the notifications field.") .'</p>';
      return $help;
    }
    else {
      $help = '<h3>'. t('Reading Response') .'</h3>';
      $help .= '<p>'. t("The readingresponse lets your team communicate by posting updates and discussing issues. It is a great place for sharing progress, discussing challenges, and exploring ideas.") .'</p>';
      return $help;
    }
  }
}


/**
* Implementation of hook_init().
*/
function atrium_readingresponse_init() {
  drupal_add_css(drupal_get_path('module', 'atrium_readingresponse') .'/atrium_readingresponse.css');
}